<?php
if(!defined('ABSPATH'))exit;
function bywp_admin_label(string $fa,string $en):string{return str_starts_with(get_locale(),'fa')?$fa:$en;}
function bywp_validate_settings(array $input,array $old):array{
 $url=trim((string)($input['endpoint']??''));if(!filter_var($url,FILTER_VALIDATE_URL)||parse_url($url,PHP_URL_SCHEME)!=='https'||parse_url($url,PHP_URL_USER)||parse_url($url,PHP_URL_QUERY)||parse_url($url,PHP_URL_FRAGMENT))throw new RuntimeException('invalid_endpoint');
 $key=trim((string)($input['secret']??''));if($key==='')$key=$old['secret']??'';if($key!==''&&!preg_match('/^[a-f0-9]{64}$/D',$key))throw new RuntimeException('invalid_secret');if(!empty($input['enabled'])&&$key==='')throw new RuntimeException('missing_secret');
 return ['checkout_enabled'=>!empty($input['checkout_enabled']),'profile_sync'=>!empty($input['profile_sync']),'unified_forms'=>!empty($input['unified_forms']),'enabled'=>!empty($input['enabled']),'endpoint'=>$url,'secret'=>$key];
}
function bywp_admin_page():void{
 if(!current_user_can('manage_options'))wp_die('Forbidden');$notice='';$error=false;$c=bywp_config();
 if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
  check_admin_referer('bonye_bridge_settings');
  try{
   if(($_POST['operation']??'')==='save'){$c=bywp_validate_settings(wp_unslash($_POST),$c);update_option('bonye_bridge_settings',$c,false);if(class_exists('WooCommerce')){try{bywp_checkout_capabilities();}catch(Throwable $ignored){}}$notice=bywp_admin_label('تنظیمات ذخیره شد.','Settings saved.');}
   elseif(($_POST['operation']??'')==='test'){
    bywp_call(['action'=>'meta'],true);if($c['enabled']&&class_exists('WooCommerce'))bywp_checkout_capabilities();delete_option('bonye_bridge_last_error');
    $notice=bywp_admin_label('ارتباط با بنیه و کلید مشترک تأیید شد. پیامکی ارسال و حسابی ایجاد نشد.','Central connection and shared secret verified. No SMS or account was created.');
   }else throw new RuntimeException('invalid_action');
  }catch(Throwable $e){$error=true;$messages=['invalid_endpoint'=>['نشانی باید HTTPS و بدون پارامتر یا نام کاربری باشد.','Endpoint must use HTTPS without query or user credentials.'],'invalid_secret'=>['کلید باید ۶۴ کاراکتر هگز باشد.','Secret must be 64 hexadecimal characters.'],'missing_secret'=>['ابتدا کلید مشترک را وارد کنید.','Enter the shared secret first.'],'bridge_unauthorized'=>['کلید مشترک دو طرف یکسان نیست یا ساعت سرورها همگام نیست.','Shared secrets differ or server clocks are out of sync.'],'bridge_disabled'=>['ورود یکپارچه را در پنل بنیه هم فعال کنید.','Enable unified login in the central panel too.'],'api_disabled'=>['API بنیه خاموش است.','The central API is disabled.']];$m=$messages[$e->getMessage()]??['ارتباط تأیید نشد؛ نشانی، HTTPS، فعال بودن سرویس مرکزی و کلید را بررسی کنید.','Connection not verified; check endpoint, HTTPS, central service and secret.'];$notice=bywp_admin_label($m[0],$m[1]);}
 }
 ?><div class="wrap"><h1><?=esc_html(bywp_admin_label('ورود یکپارچه بنیه','bonYe unified login'))?></h1>
 <?php if($notice):?><div class="notice <?=$error?'notice-error':'notice-success'?>"><p><?=esc_html($notice)?></p></div><?php endif;?>
 <div style="max-width:850px;background:white;padding:24px;border:1px solid #ddd;border-radius:10px"><p><?=esc_html(bywp_admin_label('بنیه مرجع حساب مشتری و باشگاه است. این افزونه فقط ورود همان مشتری به سایت را انجام می‌دهد.','bonYe owns customer identity and loyalty; this plugin signs the same customer into the website.'))?></p>
 <p><strong><?=esc_html(bywp_admin_label('وضعیت: ','Status: '))?></strong><?=esc_html(bywp_admin_label($c['enabled']?'روشن':'خاموش',$c['enabled']?'Enabled':'Disabled'))?> · <?=esc_html(bywp_admin_label($c['secret']!==''?'کلید تنظیم شده':'کلید تنظیم نشده',$c['secret']!==''?'Secret configured':'Secret missing'))?></p>
 <form method="post"><?php wp_nonce_field('bonye_bridge_settings');?><input type="hidden" name="operation" value="save"><table class="form-table"><tr><th><?=esc_html(bywp_admin_label('فعال بودن ورود یکپارچه','Enable unified login'))?></th><td><label><input type="checkbox" name="enabled" value="1" <?=$c['enabled']?'checked':''?>> <?=esc_html(bywp_admin_label('نمایش ورود بنیه و پذیرش ورود مشتری','Show bonYe login and accept customer sign-in'))?></label></td></tr>
 <tr><th><?=esc_html(bywp_admin_label('خرید فوری اپ','App quick buy'))?></th><td><label><input type="checkbox" name="checkout_enabled" value="1" <?=$c['checkout_enabled']?'checked':''?>> <?=esc_html(bywp_admin_label('پذیرش لینک امن خرید اپ (قرارداد 0.2.1)','Accept secure app checkout links (contract 0.2.1)'))?></label><p class="description"><?=esc_html(bywp_admin_label('مرکزی 53.2.0 لازم است. در پنل API بنیه هم روشن کنید و تست ارتباط را بزنید. اعلام آمادگی هر چهار دقیقه با WP-Cron تمدید می‌شود و پس از پنج دقیقه اعتبارش پایان می‌یابد. واحد پول باید با قرارداد مرکزی IRR سازگار باشد.','Requires central 53.2.0. Enable centrally and test the connection. WP-Cron refreshes readiness every four minutes; it expires after five minutes. Currency must match central IRR.'))?></p></td></tr>
 <tr><th><?=esc_html(bywp_admin_label('اطلاعات و آدرس‌ها','Profile and addresses'))?></th><td><label><input type="checkbox" name="profile_sync" value="1" <?=$c['profile_sync']?'checked':''?>> <?=esc_html(bywp_admin_label('همگام‌سازی اطلاعات مشتری و آدرس صورتحساب و ارسال','Synchronize customer profile, billing and shipping addresses'))?></label></td></tr>
 <tr><th><?=esc_html(bywp_admin_label('ثبت‌نام و خرید یکپارچه','Unified registration and checkout'))?></th><td><label><input type="checkbox" name="unified_forms" value="1" <?=$c['unified_forms']?'checked':''?>> <?=esc_html(bywp_admin_label('فرم حساب کاربری و خرید را به ورود بنیه هدایت کن','Route account and checkout pages to bonYe login'))?></label><p class="description"><?=esc_html(bywp_admin_label('ثبت‌نام مشتری از بنیه انجام می‌شود و خرید مهمان خاموش می‌شود. حساب قدیمی سایت برای اتصال اولیه حفظ می‌شود.','Registration uses central verification and guest checkout is disabled. Existing website accounts remain available for initial linking.'))?></p></td></tr>
<tr><th><label for="by-endpoint"><?=esc_html(bywp_admin_label('نشانی اتصال بنیه','bonYe endpoint'))?></label></th><td><input id="by-endpoint" type="url" name="endpoint" class="regular-text" dir="ltr" required value="<?=esc_attr($c['endpoint']?:'https://bonye.pet/totallsystem/website_bridge.php')?>"><p class="description">https://bonye.pet/totallsystem/website_bridge.php</p></td></tr>
 <tr><th><label for="by-secret"><?=esc_html(bywp_admin_label('کلید مشترک','Shared secret'))?></label></th><td><input id="by-secret" type="password" name="secret" class="regular-text" autocomplete="new-password" dir="ltr" value=""><p class="description"><?=esc_html(bywp_admin_label('کلید را از پنل بنیه ← اتصال WooCommerce ← ورود یکپارچه کپی کنید. خالی گذاشتن، کلید قبلی را حفظ می‌کند.','Copy from bonYe → WooCommerce → Unified login. Leave blank to retain the current secret.'))?></p></td></tr></table><?php submit_button(bywp_admin_label('ذخیره تنظیمات','Save settings'));?></form>
 <hr><form method="post"><?php wp_nonce_field('bonye_bridge_settings');?><input type="hidden" name="operation" value="test"><?php submit_button(bywp_admin_label('تست ارتباط و کلید — بدون ارسال پیامک','Test connection and secret — no SMS'),'secondary');?></form>
 <p><?=esc_html(bywp_admin_label('تست از تنظیمات ذخیره‌شده استفاده می‌کند؛ ابتدا ذخیره کنید. تنظیمات قدیمی wp-config.php تا زمان ذخیره در این صفحه پشتیبانی می‌شوند. خاموش کردن، نشست‌های قبلی سایت را خارج نمی‌کند.','The test uses saved settings; save first. Existing wp-config.php configuration remains supported until overridden here. Disabling does not log out existing website sessions.'))?></p>
 <?php $diag=get_option('bonye_bridge_last_error',[]);if(is_array($diag)&&!empty($diag['code'])):?><p><strong><?=esc_html(bywp_admin_label('آخرین خطای اتصال:','Last connection error:'))?></strong> <code><?=esc_html($diag['code'])?></code> · HTTP <?=(int)($diag['status']??0)?> · <code><?=esc_html($diag['request_id']??'')?></code></p><?php endif;?>
 <p><a class="button" href="<?=esc_url(home_url('/?bonye_login=1'))?>" target="_blank" rel="noopener"><?=esc_html(bywp_admin_label('باز کردن صفحه ورود مشتری','Open customer login page'))?></a></p>
 </div></div><?php
}
add_action('admin_menu',function(){add_options_page('bonYe','ورود یکپارچه bonYe','manage_options','bonye-customer-bridge','bywp_admin_page');});
add_filter('plugin_action_links_'.plugin_basename(__DIR__.'/bonye-customer-bridge.php'),function($links){array_unshift($links,'<a href="'.esc_url(admin_url('options-general.php?page=bonye-customer-bridge')).'">'.esc_html(bywp_admin_label('تنظیمات','Settings')).'</a>');return $links;});
