<?php
if(!defined('ABSPATH'))exit;
add_action('woocommerce_account_dashboard',function(){
 if(!bywp_config()['enabled'])return;$id=get_current_user_id();if(!$id)return;$cp=(int)get_user_meta($id,'_bonye_counterparty',true);$mobile=(string)get_user_meta($id,'_bonye_mobile_verified',true);
 if(!$cp||!$mobile){echo '<p><a href="'.esc_url(home_url('/?bonye_login=1')).'">'.esc_html(bywp_admin_label('اتصال حساب به بنیه و تأیید موبایل','Link to bonYe and verify mobile')).'</a></p>';return;}
 try{$page=max(1,min(10000,(int)($_GET['bonye_page']??1)));$r=bywp_call(['action'=>'customer_area','user_id'=>$id,'counterparty_id'=>$cp,'mobile'=>$mobile,'page'=>$page]);$club=$r['club'];$orders=$r['orders'];
 $detail=null;if(isset($_GET['bonye_invoice'])){$invoice=(string)$_GET['bonye_invoice'];if(!ctype_digit($invoice)||strlen($invoice)>18||(int)$invoice<1)throw new RuntimeException('invalid_order');$detail=bywp_call(['action'=>'customer_order','user_id'=>$id,'counterparty_id'=>$cp,'mobile'=>$mobile,'order_id'=>(int)$invoice]);}
 ?><section><h2><?=esc_html(bywp_admin_label('باشگاه و همه خریدهای بنیه','bonYe club and all purchases'))?></h2><p><?=esc_html(bywp_admin_label('امتیاز: ','Points: '))?><?=esc_html((string)$club['points'])?> · <?=esc_html(bywp_admin_label('سطح: ','Tier: '))?><?=esc_html($club['tier']['name']??'—')?> · <?=esc_html(bywp_admin_label('اعتبار خرید: ','Purchase credit: '))?><?=esc_html($club['credit']['amount'])?> IRR</p><p><?=esc_html(bywp_admin_label('این اطلاعات مستقیماً از بنیه خوانده می‌شود. سفارش سایت پس از همگام‌سازی در این فهرست ظاهر می‌شود. مبلغ‌ها به ریال هستند.','Read directly from bonYe. Website orders appear here after synchronization. Amounts are in Iranian rial.'))?></p>
 <table class="shop_table"><thead><tr><?php foreach([['فاکتور','Invoice'],['تاریخ','Date'],['مبدأ / شعبه','Origin / branch'],['پرداخت / وضعیت','Payment / status'],['مبلغ خالص (ریال)','Net amount (IRR)']] as $names):?><th><?=esc_html(bywp_admin_label(...$names))?></th><?php endforeach;?></tr></thead><tbody><?php if(!$orders['items']):?><tr><td colspan="5"><?=esc_html(bywp_admin_label('خریدی هنوز در بنیه ثبت نشده است.','No central purchases yet.'))?></td></tr><?php endif;foreach($orders['items'] as $o):?><tr><td><a href="<?=esc_url(add_query_arg('bonye_invoice',(int)$o['id'],wc_get_page_permalink('myaccount')))?>"><?=esc_html($o['invoice_no'])?></a></td><td><?=esc_html($o['invoice_date'])?></td><td><?=esc_html(($o['purchase_origin']??'—').' · '.($o['branch_name']??'—'))?></td><td><?=esc_html(($o['payment_status']??'—').' · '.$o['status'])?></td><td><?=esc_html($o['net_amount'])?></td></tr><?php endforeach;?></tbody></table>
 <p><?php if($page>1):?><a href="<?=esc_url(add_query_arg('bonye_page',$page-1,wc_get_page_permalink('myaccount')))?>"><?=esc_html(bywp_admin_label('قبلی','Previous'))?></a><?php endif;?> · <?=$page?> <?php if($page*20<$orders['total']):?><a href="<?=esc_url(add_query_arg('bonye_page',$page+1,wc_get_page_permalink('myaccount')))?>"><?=esc_html(bywp_admin_label('بعدی','Next'))?></a><?php endif;?></p></section><?php
 if($detail)require __DIR__.'/customer-order-view.php';
 }catch(Throwable $e){echo '<p role="alert">'.esc_html(bywp_error_message($e)).'</p>';}
});
