<?php if(!defined('ABSPATH'))exit;$fa=str_starts_with(get_locale(),'fa');$label=fn($f,$e)=>bywp_admin_label($f,$e);$modes=['login'=>['ورود با پیامک','SMS login'],'password'=>['ورود با رمز بنیه','bonYe password'],'register'=>['ثبت‌نام','Register'],'recovery'=>['بازیابی رمز','Recover password']];?>
<!doctype html><html lang="<?=$fa?'fa':'en'?>" dir="<?=$fa?'rtl':'ltr'?>"><head><meta name="viewport" content="width=device-width, initial-scale=1"><meta charset="utf-8"><title>bonYe</title><style>body{font:16px Tahoma;background:#f4f7f6;margin:0;color:#183f42}main{max-width:460px;margin:5vh auto;padding:28px;background:white;border-radius:18px;box-shadow:0 8px 36px #173d4210}input,button{box-sizing:border-box;width:100%;padding:12px;margin:8px 0;border:1px solid #cad7d7;border-radius:8px}button{background:#245d60;color:white;border:0;cursor:pointer}nav{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:20px}nav a{padding:8px;color:#245d60;text-decoration:none;background:#edf5f5;border-radius:6px}nav a.active{background:#245d60;color:white}.message{padding:12px;background:#fff8e4;overflow-wrap:anywhere}.muted{font-size:13px;line-height:1.8;color:#596b6d}a{color:#245d60}</style></head><body><main><h1>bonYe!</h1><p><?=esc_html($label('یک حساب برای سایت، اپ و باشگاه مشتریان','One identity for the store, app and loyalty club'))?></p>
<nav><?php foreach($modes as $value=>$names):?><a class="<?=$mode===$value?'active':''?>" href="<?=esc_url(home_url('/?bonye_login=1&mode='.$value))?>"><?=esc_html($label(...$names))?></a><?php endforeach;?></nav>
<?php if($message):?><p class="message" role="alert"><?=esc_html($message)?></p><?php endif;?>
<?php if($claim):?><p><?=esc_html(sprintf(bywp_t('ادامه با حساب %s، شماره %s%s؟'),$claim['name'],substr($claim['mobile'],0,4).'***'.substr($claim['mobile'],-4),is_user_logged_in()?bywp_t(' و اتصال به حساب فعلی سایت'):''))?></p><form method="post"><input type="hidden" name="bonye_bridge" value="confirm"><input type="hidden" name="csrf" value="<?=esc_attr($csrf)?>"><button><?=esc_html(bywp_t('تأیید و ادامه خرید'))?></button></form>
<?php elseif(!empty($flow['challenge'])):$mode=$flow['mode'];?><form method="post"><input type="hidden" name="bonye_bridge" value="verify"><input type="hidden" name="csrf" value="<?=esc_attr($csrf)?>"><label><?=esc_html(bywp_t('کد پیامک'))?></label><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required>
<?php if($mode==='register'):?><label><?=esc_html($label('نام و نام خانوادگی','Full name'))?></label><input name="name" maxlength="160" autocomplete="name" required><?php endif;?>
<?php if(in_array($mode,['register','recovery'],true)):?><label><?=esc_html($label('رمز جدید بنیه','New bonYe password'))?></label><input type="password" name="new_password" autocomplete="new-password" minlength="12" maxlength="72" required><label><?=esc_html($label('تکرار رمز','Repeat password'))?></label><input type="password" name="password_repeat" autocomplete="new-password" required><p class="muted"><?=esc_html($label('حداقل ۱۲ و حداکثر ۷۲ بایت. رمز در بنیه ثبت می‌شود؛ رمز وردپرس کپی نمی‌شود.','12–72 bytes. The password is stored centrally, not copied to WordPress.'))?></p><?php endif;?><button><?=esc_html(bywp_t('تأیید موبایل'))?></button></form><a href="<?=esc_url(home_url('/?bonye_login=1&mode='.$mode.'&restart=1'))?>"><?=esc_html($label('شروع دوباره / درخواست کد تازه','Start again / request new code'))?></a>
<?php else:?><form method="post" id="bywp-main"><input type="hidden" name="bonye_bridge" value="<?=$mode==='password'?'password':'request'?>"><input type="hidden" name="mode" value="<?=esc_attr($mode)?>"><input type="hidden" name="csrf" value="<?=esc_attr($csrf)?>"><label><?=esc_html(bywp_t('شماره موبایل بنیه'))?></label><input name="mobile" inputmode="tel" autocomplete="tel" required>
<?php if($mode==='password'):?><label><?=esc_html($label('رمز حساب بنیه','bonYe account password'))?></label><input type="password" name="password" autocomplete="current-password" required><p class="muted"><?=esc_html($label('اگر فقط حساب قدیمی سایت دارید، از لینک پایین وارد شوید.','For an existing website-only account, use the link below.'))?></p><?php endif;?><button><?=esc_html($mode==='password'?$label('ورود','Sign in'):bywp_t('دریافت کد ورود'))?></button></form>
<form method="post" id="bywp-handoff" hidden><input type="hidden" name="bonye_bridge" value="consume"><input type="hidden" name="csrf" value="<?=esc_attr($csrf)?>"><input type="hidden" name="ticket" id="bywp-ticket"><button><?=esc_html(bywp_t('ادامه از اپ'))?></button></form><script>const t=new URLSearchParams(location.hash.slice(1)).get('bonye_ticket');history.replaceState(null,'',location.pathname+location.search);if(t&&/^[a-f0-9]{64}$/.test(t)){document.getElementById('bywp-ticket').value=t;document.getElementById('bywp-handoff').hidden=false;document.getElementById('bywp-main').hidden=true;}</script><?php endif;?>
<p><a href="<?=esc_url(wp_login_url(home_url('/?bonye_login=1')))?>"><?=esc_html(bywp_t('ورود با حساب قبلی سایت'))?></a></p><p class="muted"><?=esc_html($label('خرید و امتیاز از همان حساب مرکزی پیگیری می‌شوند؛ ثبت سفارش و پرداخت در سایت انجام می‌شود.','Purchases and points use the same central customer; orders and payment remain on the website.'))?></p></main></body></html>
